/**
 * Proactive alert types, in-memory log, and SSE client registry.
 *
 * Alerts are generated by the monitor (monitor.ts) and broadcast to all
 * connected browser clients over Server-Sent Events. They are also kept in
 * a bounded in-memory log so late-joining clients can load recent history.
 */
import { randomUUID } from "node:crypto";

export type AlertSeverity = "info" | "warning" | "urgent";

export interface ProactiveAlert {
  id: string;
  timestamp: string;
  location: string;
  businessType: string;
  severity: AlertSeverity;
  signal: string;           // what triggered it: "weather" | "transit" | "demand" | "event"
  title: string;
  body: string;
  actions: string[];
  delta: {
    metric: string;
    from: string;
    to: string;
  };
}

// ---- In-memory alert log (last 100 alerts, newest first) --------------------
const MAX_LOG = 100;
const alertLog: ProactiveAlert[] = [];

export function logAlert(alert: ProactiveAlert): void {
  alertLog.unshift(alert);
  if (alertLog.length > MAX_LOG) alertLog.length = MAX_LOG;
}

export function recentAlerts(n = 20): ProactiveAlert[] {
  return alertLog.slice(0, n);
}

// ---- SSE client registry ----------------------------------------------------
// Each connected browser tab gets a controller it can write to.
const sseClients = new Map<string, ReadableStreamDefaultController<string>>();

export function registerSseClient(controller: ReadableStreamDefaultController<string>): string {
  const id = randomUUID();
  sseClients.set(id, controller);
  return id;
}

export function unregisterSseClient(id: string): void {
  sseClients.delete(id);
}

// ---- Broadcast an alert to all connected clients ----------------------------
export function broadcastAlert(alert: ProactiveAlert): void {
  logAlert(alert);
  const payload = `data: ${JSON.stringify(alert)}\n\n`;
  for (const [id, ctrl] of sseClients) {
    try {
      ctrl.enqueue(payload);
    } catch {
      // Client disconnected mid-stream — clean up.
      sseClients.delete(id);
    }
  }
  console.log(`[alert] ${alert.severity.toUpperCase()} · ${alert.location} · ${alert.title}`);
}

// ---- Alert factory helpers --------------------------------------------------
export function makeAlert(
  params: Omit<ProactiveAlert, "id" | "timestamp">,
): ProactiveAlert {
  return { id: randomUUID(), timestamp: new Date().toISOString(), ...params };
}

export function sseClientCount(): number {
  return sseClients.size;
}
